// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// id_low_search
arma::vec id_low_search(arma::vec& V);
RcppExport SEXP _LCPcore_id_low_search(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(id_low_search(V));
    return rcpp_result_gen;
END_RCPP
}
// q_low_compute
arma::vec q_low_compute(arma::vec& id_low, arma::mat& Qcumsum);
RcppExport SEXP _LCPcore_q_low_compute(SEXP id_lowSEXP, SEXP QcumsumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type id_low(id_lowSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Qcumsum(QcumsumSEXP);
    rcpp_result_gen = Rcpp::wrap(q_low_compute(id_low, Qcumsum));
    return rcpp_result_gen;
END_RCPP
}
// LCP_construction_path_distance
List LCP_construction_path_distance(arma::vec& V, arma::vec& id_low, arma::vec& q_low, arma::vec& qn, arma::mat& Hnew, arma::mat& HnewT);
RcppExport SEXP _LCPcore_LCP_construction_path_distance(SEXP VSEXP, SEXP id_lowSEXP, SEXP q_lowSEXP, SEXP qnSEXP, SEXP HnewSEXP, SEXP HnewTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type id_low(id_lowSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type q_low(q_lowSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Hnew(HnewSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type HnewT(HnewTSEXP);
    rcpp_result_gen = Rcpp::wrap(LCP_construction_path_distance(V, id_low, q_low, qn, Hnew, HnewT));
    return rcpp_result_gen;
END_RCPP
}
// LCP_construction_distance_loop
List LCP_construction_distance_loop(arma::vec& V, arma::mat& Qcumsum, arma::mat& H);
RcppExport SEXP _LCPcore_LCP_construction_distance_loop(SEXP VSEXP, SEXP QcumsumSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Qcumsum(QcumsumSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(LCP_construction_distance_loop(V, Qcumsum, H));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _LCPcore_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _LCPcore_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _LCPcore_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _LCPcore_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
